# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-19 13:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='loginpage',
            new_name='signupp',
        ),
    ]
