# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-22 16:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0002_auto_20180819_1833'),
    ]

    operations = [
        migrations.AddField(
            model_name='signupp',
            name='vote',
            field=models.TextField(blank=True, null=True),
        ),
    ]
