# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-23 14:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0003_signupp_vote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signupp',
            name='auth',
        ),
        migrations.RemoveField(
            model_name='signupp',
            name='password',
        ),
    ]
