# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-23 14:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0004_auto_20180823_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signupp',
            name='username',
            field=models.TextField(unique=True),
        ),
    ]
