# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-29 16:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0005_auto_20180823_1947'),
    ]

    operations = [
        migrations.AddField(
            model_name='signupp',
            name='password',
            field=models.TextField(default=12345),
            preserve_default=False,
        ),
    ]
