# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-30 09:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0006_signupp_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signupp',
            name='password',
        ),
    ]
