# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-12-01 06:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0007_remove_signupp_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signupp',
            name='vote',
        ),
        migrations.AddField(
            model_name='signupp',
            name='confirm_bucks',
            field=models.TextField(default=500),
        ),
        migrations.AddField(
            model_name='signupp',
            name='name',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='signupp',
            name='provision_bucks',
            field=models.TextField(default=0),
        ),
    ]
