# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-12-08 13:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0009_eventlist_eventpass'),
    ]

    operations = [
        migrations.DeleteModel(
            name='eventlist',
        ),
        migrations.DeleteModel(
            name='eventpass',
        ),
    ]
